notifications: 
    email: false

sudo: required
language: rust

before_install:
    - sudo apt-get install -y rubygems
    - sudo gem install os
    - git clone https://github.com/stpettersens/full-monkey.git
    - cd full-monkey
    - rake && sudo cp target/release/fm /usr/bin
    - cd ..
    - fm --version
    - ruby --version
    - rake --version

script:
    - rake
    - rake test
